### PR TITLE
Add problem styling

### PR DESCRIPTION
**Pull request by PrestonRooker**
Updated the css styling of add-problem page to match figma.

### CODE REVIEW

**Comment by TJ178** [comment]
image
image


Could you fix this so that the left side has fixed vertical spacing? (or just make it so that the description box cannot be resized)

**Review by TJ178 — CHANGES_REQUESTED** [review]
above^

**Comment by PrestonRooker** [comment]
Bug should be fixed, please review.

**Review by TJ178 — APPROVED** [review]
lgtm

**Pull request merged**
